#!/usr/bin/env bash
# This Bash script facilitates secure file transfer from a client to a server using scp

# Check if all required parameters are provided
if [ "$#" -eq 4 ]; then
    # Transfer the specified file to the server's home directory using scp
    # $1: Path to the file to be transferred
    # $2: IP address of the destination server
    # $3: Username for scp connection
    # $4: Path to the SSH private key for authentication
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
else
    # Display usage instructions if parameters are incorrect or incomplete
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi