#!/usr/bin/env bash
# This script transfers a file from our client to a server

# Check if all parameters are present
# If no, exit
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Gather input
FILE=$1
IP=$2
USER=$3
KEY=$4

# Disable strict host key checking
OPTIONS='-o StrictHostKeyChecking=no'

# Transfer file
scp $OPTIONS -i "$KEY" "$FILE" "$USER@$IP:~/"