#!/usr/bin/env bash
# This script installs nginx, creates a custom index page, sets up a redirection, and restarts the service

# Update the package lists for upgrades and new package installations
sudo apt-get update -y

# Install nginx
sudo apt-get install nginx -y

# Remove the default nginx index page
sudo rm /var/www/html/index.nginx-debian.html

# Create a new index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Set up a redirection from /redirect_me to another page
echo "server {
    listen 80;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    location / {
        root /var/www/html;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart