#!/usr/bin/env bash
# This script updates the system and installs Nginx

# Update package lists and upgrade installed packages
sudo apt update
sudo apt upgrade -y

# Install Nginx
sudo apt install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html

tring_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/NEAZYIT permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Add custom HTTP response header to Nginx configuration
sudo sed -i "/server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Test Nginx configuration
sudo nginx -t

# Restart Nginx service
sudo service nginx restart
