#!/usr/bin/env bash
# Script to install and configure HAProxy

# Install HAProxy
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg >/dev/null
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend main
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server web-01 373243-web-01:80 check
    server web-02 373243-web-02:80 check
EOF

# Restart HAProxy service
sudo service haproxy restart
