#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument.

if [ "$1" ]; then
    ip_address="$1"
    echo "Pinging $ip_address 5 times..."
    ping -c 5 "$ip_address"
else
    echo "Usage: $0 {IP_ADDRESS}"
fi
