#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument.

# Check if an argument (IP address) is provided
if [ "$1" ]; then
    # If an IP address is provided as the first argument, ping it 5 times
    echo "Pinging IP address: $1 5 times..."
    ping -c 5 "$1"
else
    # If no argument is provided, display a usage message
    echo "Usage: $0 {IP_ADDRESS}"
fi
