#!/usr/bin/env bash
# Script to manage the 'manage_my_process' script.
#   start: Starts 'manage_my_process', stores PID, and displays "started."
#   stop: Stops 'manage_my_process,' deletes PID file, and displays "stopped."
#   restart: Stops 'manage_my_process,' deletes PID file, starts it, and displays "restarted."
#   If no or invalid arguments provided, displays usage instructions.

if [ "$1" == "start" ]; then
  # Start 'manage_my_process', store its PID, and show "started" message.
  ./manage_my_process &
  echo $$ > /var/run/my_process.pid
  echo "manage_my_process started"

elif [ "$1" == "stop" ]; then
  # Stop 'manage_my_process,' remove PID file, and show "stopped" message.
  kill "$(pgrep -f /manage_my_process)"
  rm /var/run/my_process.pid
  echo "manage_my_process stopped"

elif [ "$1" == "restart" ]; then
  # Restart 'manage_my_process': stop, remove PID file, start, store new PID, and show "restarted" message.
  kill "$(pgrep -f /manage_my_process)"
  rm /var/run/my_process.pid
  ./manage_my_process &
  echo $$ > /var/run/my_process.pid
  echo "manage_my_process restarted"

else
  # Display usage instructions for invalid or missing arguments.
  echo "Usage: $0 {start|stop|restart}"
fi
