#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Find the PID of the process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [ -n "$pid" ]; then
    echo "Terminating 4-to_infinity_and_beyond..."
    kill "$pid"
else
    echo "4-to_infinity_and_beyond is not running."
fi
