#!/usr/bin/env bash

# This script displays information about users from the /etc/passwd file.
# It uses the while loop and IFS to extract and format the data.

# Set the Internal Field Separator (IFS) to ":" to split lines into fields.
IFS=":"

# Open the /etc/passwd file for reading.
while read -r username passwd uid gid user_info home shell
do
    # Extract and format the required information.
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell."
    echo "$uid's place is protected by the passcode $passwd, more info about the user here: $user_info"
done < /etc/passwd
