#!/bin/bash
# This script displays the content of the file /etc/passwd, using the while loop + IFS.

while read -r username password user_id group_id home_directory shell; do
  echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $command."
done < /etc/passwd
