#!/usr/bin/env bash
# This script parses and sorts Apache log data by IP and HTTP status code.

# Use awk to process the log file, group by IP and HTTP status code, and count occurrences.
awk '{ip[$1][$9]++} END {for (i in ip) {for (j in ip[i]) {print ip[i][j], i, j}}}' /path/to/apache-access.log | sort -nr
