#!/usr/bin/env bash
# This script displays numbers and superstitions based on the loop iteration number.

counter=1
max_iterations=20
while [ $counter -le $max_iterations ]
do
	case $counter in
		4)
			echo "$counter"
			echo "bad luck from China"
			;;
		9)
			echo "$counter"
			echo "bad luck from Japan"
			;;
		17)
			echo "$counter"
			echo "bad luck from Italy"
			;;
		*)
			echo "$counter"
			;;
	esac
	counter=$((counter+1))
done
