#!/usr/bin/env bash
# This script configures DNS resolution for localhost and facebook.com

# Create a backup of the original /etc/hosts file
cp /etc/hosts ~/hosts.new

# Use sed to replace 127.0.0.1 with 127.0.0.2 in the temporary file
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new

# Append the resolution for facebook.com to the temporary file
echo "8.8.8.8 facebook.com" >> ~/hosts.new

# Forcefully copy the modified temporary file to /etc/hosts
cp -f ~/hosts.new /etc/hosts
