#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine

# Use the 'ifconfig' command to get network interface information
ifconfig | grep -oE 'inet (addr:)?([0-9]*\.){3}[0-9]*' | awk '{print $2}'
