#!/usr/bin/env bash
# Replace /etc/nginx/nginx.conf user directive
sed -i "s/^user root;/user nginx;/" /etc/nginx/nginx.conf

# Set nginx user and group for process
runuser -l nginx -c "nginx -g 'daemon'; kill $(pgrep -f '^nginx')"

# Verify process owner
ps auxff | grep nginx | grep -v grep
