#!/usr/bin/env bash
# Adjusts Nginx configuration for user and port, then starts the service
sudo sed -i -e 's/#user www-data/user nginx/' -e 's/80/8080/g' /etc/nginx/nginx.conf /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo pkill apache2
sudo -u nginx service nginx start
